Repository openscilab/opr, pull requests merged in 2024-11, with the labels that each got.

#24 Document
  AUTHORS.md
  CHANGELOG.md
  README.md
  otherfiles/logo.png
  otherfiles/meta.yaml
  setup.py
Labels: documentation

#25 Codecov
  .github/workflows/test.yml
Labels: minor, test

#26 limit gh action execution
  .github/workflows/test.yml
Labels: enhancement, minor

#27 Version 0.1
  CHANGELOG.md
  README.md
Labels: release

#30 Equality
  CHANGELOG.md
  opr/primer.py
  tests/test_operations.py
Labels: enhancement
