Repository openscilab/opr, pull requests merged in 2024-12, with the labels that each got.

#32 GC Clamp Property Added to Primer Class
  CHANGELOG.md
  README.md
  opr/functions.py
  opr/primer.py
  tests/test_calculations.py
Labels: enhancement, new feature

#33 Single runs
  CHANGELOG.md
  README.md
  opr/functions.py
  opr/primer.py
  tests/test_calculations.py
Labels: new feature

#35 Refactor/property
  CHANGELOG.md
  opr/params.py
  opr/primer.py
Labels: minor, refactoring
