Repository openscilab/opr, pull requests merged in 2025-02, with the labels that each got.

#47 Minor update
  CHANGELOG.md
  README.md
  opr/functions.py
  opr/primer.py
  tests/test_calculations.py
Labels: minor, refactoring

#48 Version 0.3
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  opr/params.py
  otherfiles/meta.yaml
  otherfiles/version_check.py
  setup.py
Labels: release

#51 Add/salt adjusted
  CHANGELOG.md
  README.md
  opr/functions.py
  opr/primer.py
  tests/test_calculations.py
Labels: new feature, minor
