Repository openscilab/opr, pull requests merged in 2025-06, with the labels that each got.

#66 Add/thermodynamics constants
  CHANGELOG.md
  README.md
  opr/functions.py
  opr/primer.py
  tests/test_cache.py
  tests/test_calculations.py
Labels: enhancement, new feature

#67 Update/dna to protein
  CHANGELOG.md
  README.md
  opr/functions.py
  opr/params.py
  opr/primer.py
  tests/test_operations.py
Labels: enhancement

#70 Type Hint Added to The Library Modules
  CHANGELOG.md
  opr/functions.py
  opr/primer.py
  otherfiles/version_check.py
  setup.py
Labels: documentation, enhancement
