Repository openscilab/opr, pull requests merged in 2025-03, with the labels that each got.

#52 Internal Cache Flag
  CHANGELOG.md
  opr/functions.py
  opr/params.py
  opr/primer.py
  tests/test_cache.py
  tests/test_calculations.py
  tests/test_errors.py
Labels: enhancement, new feature, minor, test

#53 DNA to RNA
  CHANGELOG.md
  README.md
  opr/primer.py
  tests/test_operations.py
Labels: new feature

#54 E260 (Property) DNA Single Strand Nearest Neighbor Model Added
  CHANGELOG.md
  README.md
  opr/functions.py
  opr/params.py
  opr/primer.py
  tests/test_cache.py
  tests/test_calculations.py
Labels: enhancement, new feature

#55 Equality bug
  CHANGELOG.md
  opr/functions.py
  opr/params.py
  opr/primer.py
  tests/test_calculations.py
  tests/test_operations.py
Labels: bug, minor

#56 Contains
  CHANGELOG.md
  opr/primer.py
  tests/test_operations.py
Labels: enhancement, minor

#57 Code quality badges
  CHANGELOG.md
  README.md
Labels: documentation

#58 Version 0.4
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  opr/params.py
  otherfiles/meta.yaml
  otherfiles/version_check.py
  setup.py
Labels: release
