Repository openscilab/opr, pull requests merged in 2025-01, with the labels that each got.

#36 `__str__`
  CHANGELOG.md
  opr/functions.py
  opr/primer.py
  tests/test_operations.py
Labels: enhancement, minor

#37 Test
  CHANGELOG.md
  autopep8.bat
  autopep8.sh
  tests/test_cache.py
  tests/test_calculations.py
  tests/test_errors.py
  tests/test_operations.py
Labels: enhancement, minor, test

#38 Minor edits
  .github/CONTRIBUTING.md
  CHANGELOG.md
  README.md
  SECURITY.md
  otherfiles/version_check.py
Labels: documentation, minor, test

#39 Version 0.2
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  opr/params.py
  otherfiles/meta.yaml
  otherfiles/version_check.py
  setup.py
Labels: release

#45 Add/feature(repeats+doube_runs)
  CHANGELOG.md
  README.md
  opr/primer.py
  tests/test_cache.py
  tests/test_calculations.py
Labels: new feature

#46 Iter
  CHANGELOG.md
  opr/primer.py
  tests/test_cache.py
  tests/test_calculations.py
  tests/test_operations.py
  tests/test_property.py
Labels: enhancement
